### ISSUE TITLE
RDF vs LPG

### ISSUE THREAD

**Issue by jonoforbes** [cape-io/redux-graph#1]
Hi there,

Firstly thanks for publishing this library.

I wanted to ask however whether the choice to use RDF triple stores over a Labelled Property Graph was use case specific or a more general design choice?

**Comment by webmasterkai** [comment]
The RDF triple stores just looked like an easy way to do what I wanted. With all the development of GraphQL and related tools like Apollo with all the cache options I'm not sure a tool like redux-graph is likely to survive.

**Comment by jonoforbes** [comment]
Right sure. This isn't an issue so I will close it immediately. Just as we're building a client-side graph for a product I was curious as to your choice, as in order to somewhat mirror neo4j I'm pushing for an LPG. Thanks anyway 👍
